stages:
  - trigger

# Trigger child pipeline for catalog-service
catalog-service:
  stage: trigger
  trigger:
    include: apps/catalog-service/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/catalog-service/**/*

# Trigger child pipeline for metadata-ingestion
metadata-ingestion:
  stage: trigger
  trigger:
    include: apps/metadata-ingestion/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/metadata-ingestion/**/*
