stages:
  - secret_detection
  - trigger

include:
  - project: wisenut-research/starter/templates/gitlab-ci-template
    ref: main
    file:
      - templates/Security/Secret-Detection.gitlab-ci.yml

# Trigger child pipeline for catalog-service
catalog-service:
  stage: trigger
  trigger:
    include: apps/catalog-service/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/catalog-service/**/*

# Trigger child pipeline for metadata-ingestion
metadata-ingestion:
  stage: trigger
  trigger:
    include: apps/metadata-ingestion/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/metadata-ingestion/**/*

# Trigger child pipeline for workflow-ui
workflow-ui:
  stage: trigger
  trigger:
    include: apps/workflow-ui/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/workflow-ui/**/*
