services:
  catalog-service:
    build:
      context: .
      dockerfile: ./apps/catalog-service/Dockerfile
    image: catalog-service:dev
    restart: unless-stopped
    environment:
      LEVEL: INFO
      X_TOKEN: wisenut
      TZ: Asia/Seoul
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_HOST: postgres-174
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-datagokr}
    ports:
      - 8084:8084
    depends_on:
      - postgres-174

  metadata-ingestion:
    build:
      context: .
      dockerfile: ./apps/metadata-ingestion/Dockerfile
    image: metadata-ingestion:dev
    restart: unless-stopped
    environment:
      LEVEL: INFO
      X_TOKEN: wisenut
      TZ: Asia/Seoul
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_HOST: postgres-174
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-datagokr}
    ports:
      - 8085:8085
    depends_on:
      - postgres-174

  postgres-174:
    image: postgres:17.4
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-datagokr}
      TZ: Asia/Seoul
      LANG: en_US.UTF-8
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - pgdata-postgres17:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d # todo create table 필요할 경우

  # DB client tool 이 없을 경우, 웹에서 간편하게 사용
  adminer:
    image: adminer
    environment:
      TZ: Asia/Seoul
      LANG: en_US.UTF-8
    restart: always
    ports:
      - 8888:8080

volumes:
  pgdata-postgres17:
