stages:
  - lint
  - test

include:
  - project: wisenut-research/starter/templates/gitlab-ci-template
    ref: main
    file:
      - templates/Python/Dependency-Management.gitlab-ci.yml
      - templates/Python/Lint/Uv-Lint.gitlab-ci.yml
      - templates/Python/Test/Uv-Test.gitlab-ci.yml

variables:
  PKG_DIR: packages/active-metadata

default:
  before_script:
    - cd $PKG_DIR

.pkg-lint:
  extends: .uv-lint
  before_script:
    - !reference [default, before_script]
    - echo "Running before_script tasks for $CI_JOB_NAME"
    - apt-get update && apt-get install -y libatomic1
    - uv sync --group lint
    - source .venv/bin/activate
  rules:
    - changes:
        - $PKG_DIR/**/*

ruff-lint:
  extends: .pkg-lint
  script:
    - ruff check --target-version $PYTHON_VERSION .
  parallel:
    matrix:
      - PYTHON_VERSION: ["py311"]

pyright-lint:
  extends: .pkg-lint
  script:
    - pyright --pythonversion $PYTHON_VERSION ./
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11"]

.pkg-test:
  extends:
    - .uv-unit-test
  before_script:
    - !reference [default, before_script]
    - echo "Running before_script tasks for $CI_JOB_NAME";
    - uv sync --group dev
    - source .venv/bin/activate
  rules:
    - changes:
        - $PKG_DIR/**/*

pytest:
  extends: .pkg-test
  script:
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml -q tests
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11"]
