stages:
  - lint
  - test
  - build-and-push-app
  - container_test
  - push-to-github

include:
  - local: /.gitlab/ci/build-and-push-app.yml
  - local: /.gitlab/ci/push-to-github-registry.yml
  - project: wisenut-research/starter/templates/gitlab-ci-template
    ref: main
    file:
      - templates/Python/Dependency-Management.gitlab-ci.yml
      - templates/Python/Lint/Uv-Lint.gitlab-ci.yml
      - templates/Python/Test/Uv-Test.gitlab-ci.yml
      - templates/Security/Container-Scanning.gitlab-ci.yml

variables:
  APP_NAME: catalog-service
  APP_DIR: apps/catalog-service

default:
  before_script:
    - cd $APP_DIR

.app-lint:
  extends: .uv-lint
  before_script:
    - !reference [default, before_script]
    - echo "Running before_script tasks for $CI_JOB_NAME"
    - apt-get update && apt-get install -y libatomic1
    - uv sync --group lint
    - source .venv/bin/activate
  rules:
    - changes:
        - $APP_DIR/**/*

ruff-lint:
  extends: .app-lint
  script:
    - ruff check --target-version $PYTHON_VERSION .
  parallel:
    matrix:
      - PYTHON_VERSION: ["py311"]

pyright-lint:
  extends: .app-lint
  script:
    - pyright --pythonversion $PYTHON_VERSION ./
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11"]

.app-test:
  extends:
    - .uv-unit-test
  before_script:
    - !reference [default, before_script]
    - echo "Running before_script tasks for $CI_JOB_NAME";
    - uv sync --group test
    - source .venv/bin/activate

pytest:
  extends: .app-test
  services:
    - name: postgres:17.4
      alias: postgres
  script:
    - export POSTGRES_USER=${POSTGRES_USER:-postgres}
    - export POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    - export POSTGRES_DB=${POSTGRES_DB:-test_db}
    - export POSTGRES_HOST=${POSTGRES_HOST:-postgres}
    - export PYTHONPATH=./app
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml -v tests
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11"]

build-and-push-app:
  extends: .build-and-push-app-monorepo
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - $APP_DIR/**/*
        - packages/active-metadata/**/*

container_scanning:
  before_script: [] # GIT_STRATEGY: none이므로 cd $APP_DIR 실행 안 함
  variables:
    CS_IMAGE: "$CI_REGISTRY_IMAGE/$APP_NAME:latest"

push-to-github-registry:
  extends: .push-to-github-registry
  rules:
    - if: $CI_COMMIT_BRANCH == "github"
      changes:
        - $APP_DIR/**/*
