[project]
authors = [
    { name = "Youngwoo Choi", email = "uoise@wisenut.co.kr" },
]
maintainers = [
    { name = "Youngwoo Choi", email = "uoise@wisenut.co.kr" },
]
license = { text = "LICENSE" }
requires-python = "<3.13,>=3.9"
dependencies = [
    "active-metadata",
    "loguru<1.0.0,>=0.7.2",
    "pyyaml<7.0.0,>=6.0.2",
    "pydantic-settings<3.0.0,>=2.5.2",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "requests>=2.32.3",
    "xmltodict>=0.14.2",
    "psycopg2-binary>=2.9.10",
    "fastapi[standard]<=0.115.0",
    "lxml>=5.4.0",
]
name = "catalog-service"
version = "v1"
description = "Active Metadata Management - Catalog Service"
readme = "README.md"
keywords = [
    "python",
    "fastapi",
    "template",
    "pytest",
    "ruff",
    "pyright",
    "docker",
    "gunicorn",
    "uv",
    "mkdocs"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: AsyncIO",
    "Framework :: FastAPI",
    "Framework :: Pytest",
    "Natural Language :: Korean",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Intended Audience :: Developers",
]

[dependency-groups]
lint = [
    "ruff>=0.6.4,<1.0.0",
    "pyright>=1.1.397",
    "pre-commit>=4.0.1,<5.0.0",
    "lxml-stubs>=0.5.1",
]
test = [
    "pytest<9.0.0,>=8.3.3",
    "pytest-cov<6.0.0,>=5.0.0",
    "setuptools>=77.0.3",
    "tabulate<1.0.0,>=0.9.0",
]
gunicorn = [
    "gunicorn<24.0.0,>=23.0.0",
]
db = [
    "sqlmodel>=0.0.24",
]

[tool.uv]
default-groups = ["db"]

[tool.uv.sources]
active-metadata = { path = "../../packages/active-metadata", editable = true }

[tool.setuptools]
py-modules = ["app"]

[tool.ruff]
line-length = 125
exclude = [
    '.git',
    '__pycache__',
    '.ruff_cache',
    'docs',
    'venv',
    'tests',
    'build',
    'dist',
    './app/__init__.py',
    'gunicorn.conf.py'
]
target-version = "py311"

[tool.ruff.lint]
select = ["D"]
ignore = ['W', "D100", "D104", "D414", "D415", "D417"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.extend-per-file-ignores]
# app/src 디렉토리에서만 `D` 규칙 적용, <https://docs.astral.sh/ruff/rules/#pydocstyle-d>
"app/api/*" = ["D"]
"app/exceptions/*" = ["D"]
"app/schemas/*" = ["D"]
"app/utils/*" = ["D"]
"app/version.py" = ["D"]
"app/main.py" = ["D"]
"app/log.py" = ["D"]
"app/handlers.py" = ["D"]
"app/dependencies.py" = ["D"]
"app/constants.py" = ["D"]
"app/config.py" = ["D"]
[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.pyright]
pythonVersion = "3.11"
defineConstant = { DEBUG = true }
reportMissingImports = false
reportMissingTypeStubs = false
reportArgumentType = false
typeCheckingMode = "basic"
include = ["app"]
exclude = [
    '.git',
    '__pycache__',
    '.ruff_cache',
    '.pytest_cache',
    'docs',
    'venv',
    '.venv',
    'tests',
    'build',
    'dist',
    'pypi',
    'logs',
    'gunicorn.conf.py',
    '.cache'
]

[tool.coverage.run]
source = ["app"]
omit = [
    "app/*.py",
    "*/__init__.py",
    "app/api/examples/*.py",
    "app/exceptions/*.py",
]
