stages:
  - lint

include:
  - project: wisenut-research/starter/templates/gitlab-ci-template
    ref: main
    file:
      - templates/Python/Dependency-Management.gitlab-ci.yml
      - templates/Python/Lint/Uv-Lint.gitlab-ci.yml

variables:
  APP_NAME: metadata-ingestion
  APP_DIR: apps/metadata-ingestion

.app-lint:
  extends: .uv-lint
  before_script:
    - cd $APP_DIR
    - echo "Running before_script tasks for $CI_JOB_NAME"
    - apt-get update && apt-get install -y libatomic1
    - uv sync --group lint
    - source .venv/bin/activate
  rules:
    - changes:
        - apps/metadata-ingestion/**/*

ruff-lint:
  extends: .app-lint
  script:
    - ruff check --target-version $PYTHON_VERSION .
  parallel:
    matrix:
      - PYTHON_VERSION: ["py311"]

pyright-lint:
  extends: .app-lint
  script:
    - pyright --pythonversion $PYTHON_VERSION ./
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11"]
